# name: Create new pre-release

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# defaults:
#   run:
#     shell: bash

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set build version number
#         run: |
#           echo VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER >> $GITHUB_ENV

#       - name: Create GitHub pre-release
#         uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: v${{ env.VERSION }}
#           prerelease: true
#           title: ${{ env.VERSION }}
